# Generated by Django 3.0.4 on 2020-04-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='datePosted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_featured',
            new_name='isFeatured',
        ),
    ]
